//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lightstone.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeaveRequest
    {
        public int LeaveRequestId { get; set; }
        public int EmployeeId { get; set; }
        public System.DateTime LeaveFrom { get; set; }
        public System.DateTime LeaveTo { get; set; }
        public string LeaveDescription { get; set; }
        public Nullable<int> ActionManagerId { get; set; }
        public int RequestStatusId { get; set; }
    
        public virtual Employee ActionManager { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual RequestStatu RequestStatu { get; set; }
    }
}
